[project]
name = "micrograd"
version = "0.1.0"
description = "Implementing Karpathy's Micrograd Tutorial"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.0",
    "pytest>=8.4.0",
]
